### ISSUE TITLE
dependsOnNullOrZero not working

### ISSUE THREAD

**Issue by packytagliaferro** [epartment/nova-dependency-container#139]
I have this condition set:

```
NovaDependencyContainer::make([
                Text::make('Profile ID')->readonly(),
                Number::make('Refund'),
                Number::make('Append'),
            ])->dependsOnNullOrZero('profile_id'),
```

I can see in my database all records have `profile_id` set as `NULL` except one record but the fields show when I go to edit any record.

**Comment by ragingdave** [comment]
So I'm not sure that it's not working specifically. Typically the trigger field is outside the dependency container rather than inside because having it inside means that once it's triggered to show, it can't be unshown or vice versa depending on the field value.

I'll close for now but if moving the profile ID field outside of the container doesn't work, then we can revisit the issue.
