### ISSUE TITLE
Attach inside fields callback function with Select

### ISSUE THREAD

**Issue by shortcodes** [epartment/nova-dependency-container#52]
I woud like this package to work in this case

```
BelongsToMany::make('Features')
                ->fields(function () {
                    return [
                        NovaDependencyContainer::make([
                            Select::make('Feature Value', 'feature_value_id')->options(
                                \App\FeatureValue::where('feature_id',3)->get()->pluck('value', 'id')->toArray()
                            )->displayUsingLabels()
                        ])->dependsOn('features', '3'),

                    ];
                }),

```

Is this possible? How to achieve that?

**Comment by wize-wiz** [comment]
@shortcodes I'm trying to do the same thing, before I dive into this problem I'll just ask, have you figured it out or found another solution?

**Comment by wize-wiz** [comment]
So 2 problems .. 

First offf, there is no real problem with this package, but ... it seems the select field generated by a `BelongsToMany` field does not have a `field` property in its vue component.

https://github.com/epartment/nova-dependency-container/blob/65d3205509321b6fd04dd242e3e929b1183c82a0/resources/js/components/FormField.vue#L40

checks if the component is a so callled dependency component, where

https://github.com/epartment/nova-dependency-container/blob/65d3205509321b6fd04dd242e3e929b1183c82a0/resources/js/components/FormField.vue#L56

explicitely requires a `field` property in order to attach a watcher

https://github.com/epartment/nova-dependency-container/blob/65d3205509321b6fd04dd242e3e929b1183c82a0/resources/js/components/FormField.vue#L42

if the field property is missing, it will simply return false. So `componentIsDependency` will never catch the relationship select field and start listening for changes for the containers to react.

Now the second problem, a relationship select field does not store it's value in the vue components property `value`, where the line `$watch('attrname', function() {}` (attrname has a value of `value`) expects it to be. The selected value from a relationship select is stored in the property `selected`. Now this is just plain stupid, it has its reasons but still ;)

I'm trying to find something I can depend on, that the component is an `attach-view` component, I would add a check, something like 

```js
componentIsAttachDependency(component) {
     if(component.some-attr-attach-selects-have !== undefined) {
         component.$watch('selected', (value) => {
           // continue from here like componentIsDependency() does.
         }
     }
}
```

I'll keep this updated ..

**Comment by shortcodes** [comment]
@wize-wiz If i remember correct ( i might not) i changed relation type to hasMany (there is not much difference - mental one) and  used default nova filters in model file

**Comment by wize-wiz** [comment]
@shortcode Ok cool, but I really need these containers to work in a `BelongsToMany` setup so I'll post a working version and check if it works with all other relation fields, `HasMany` etc ;)

**Comment by wize-wiz** [comment]
Here is a working version for a `BelongsToMany` field.

https://github.com/wize-wiz/nova-dependency-container/commit/03b94ca6d0ea5bb5a478439f99b39cc083d3e5c7

Just a bogus fork, nothing serious really.

**Comment by wize-wiz** [comment]
@shortcodes clean solution

https://github.com/wize-wiz/nova-dependency-container/commit/1ca74992118cf84c8f31a40407a71e36abe2ee89

Will test other relation types in the next couple of days when I have real examples.

**Comment by wize-wiz** [comment]
Problems seems to be a bit bigger, but solved. Still at the cost of modifying a nova class, see

https://github.com/tainmar/nova-dependency-container/commit/dd446102c4beb9cde94dd3e0e421268ea0f38a79#commitcomment-35027624

`ResolvesFields` seems to be having the same problem in different scenarios with core functionality.

https://github.com/laravel/nova-issues/issues/1694
https://github.com/laravel/nova-issues/issues/1585

Oh well ..

**Comment by wize-wiz** [comment]
I have a working version with the current [v1.2.9](https://github.com/epartment/nova-dependency-container/releases/tag/1.2.9) for a `BelongsToMany` field.

Please see the [README#BelongsToMany](https://github.com/epartment/nova-dependency-container/blob/master/README.md#belongstomany-dependency) on how to use it.

If there is any other problem with this release, please open a new issue.
