### ISSUE TITLE
This is an abandoned project 💀

### ISSUE THREAD

**Issue by fede91it** [epartment/nova-dependency-container#74]
The project is abandoned and no longer works with the latest versions of Nova. There are many pull requests waiting and they have not yet been accepted. I'm afraid the author has disappeared. I would then like to create a new fork and, with everyone's help, try to fix this package to make it work again.

Who would want to help me?

**Comment by grantholle** [comment]
I can't find an alternative to this package unfortunately. Seems like a fork and new maintainers is in order...

**Comment by tainmar** [comment]
@fede91it this fork seems to be the most advanced : https://github.com/Lotfull/nova-dependency-container

**Comment by tainmar** [comment]
I forked Lotfull's fork to [https://github.com/tainmar/nova-dependency-container/tree/tainmar](https://github.com/tainmar/nova-dependency-container/tree/tainmar).

First remove epartment's project : `composer remove epartment/nova-dependency-container`

Then add the following lines to your `composer.json`

```
"repositories": [
  {
    "type": "vcs",
    "url": "https://github.com/tainmar/nova-dependency-container"
  }
],
```

Finally, `composer require epartment/nova-dependency-container:"dev-tainmar"`

**Comment by fede91it** [comment]
I see that the lotfull fork is maintained, why not use all that?

**Comment by tainmar** [comment]
Well I did not want to publish their fork to packagist.
And they are not on a specific branch so I did not manage to call it like `dev-tainmar` above.
If you have a solution, it would be great

**Comment by fede91it** [comment]
For now I have installed their fork in place of the original and everything works, it seems there is not even a problem, great!

**Comment by tainmar** [comment]
How did you do, can you show me your `composer.json` please ?

**Comment by hadinajem** [comment]
Well, the easiest thing to do is to use associative array with string keys instead of integers, it worked well in my case

This is the select component setup:
```
Select::make('Type', 'type')->options([
                "0" => 'Text',
                "1" => 'File',
            ])
```

And when setting up the container just use the indexes as strings and not integers
`->dependsOn('type', "0")`

and: 
`->dependsOn('file_type', "1")`

**Comment by wize-wiz** [comment]
@fede91it @tainmar @grantholle so what's the status here? This is not going to help the folks installing this package when all the readme's of all forks telling you to `composer require epartment/nova-dependency-container`

**Comment by tainmar** [comment]
The forks are mostly people doing things on their side. The best case would be to create a new repo and to publish it on packagist.

Otherwise, my solution there works : https://github.com/epartment/nova-dependency-container/issues/74#issuecomment-528752163

I was expecting an answer from @fede91it but nothing yet.

**Comment by wize-wiz** [comment]
@tainmar I know it works, I forked a fork from your fork.. all those forks ;)

This package needs a rewrite though..

**Comment by wize-wiz** [comment]
Ah you know what, f*ck it, I'm going to ask the company (I'm Dutch) where the guy is who published this repo. All those people on epartment seem very nice.

**Comment by tainmar** [comment]
Any news from them ? @wize-wiz 
Btw, is your fork working when creating with `belongsTo` relationship ?

**Comment by wize-wiz** [comment]
@tainmar I've asked him if he is willing to transfer the repository, anyway I've add you as a collaborator as well, at least we could merge PR's and handle issues if we time on our hands. That's least thing we can do.

**Comment by jnbn** [comment]
@d35k & @bsormagec perhaps we can help @wize-wiz  and @tainmar for the maintenance of the project?

I suggest getting a copy and continue with a new repo and a new name if @epartment don't have any plans on maintenance (instead of keeping it).

And just get help from @epartment to update the readme and refer it for the new versions for better maintenance. Otherwise we'll all have to check all the forks and decide each time...

**Comment by wize-wiz** [comment]
@jnbn That would be great; I'm going to wait till coming friday for a response on my proposal. If no response till then, setting up a new repo would be the only thing left to do.

**Comment by jnbn** [comment]
Seems like you started as contributor @wize-wiz ?

**Comment by wize-wiz** [comment]
@jnbn Yea, this needs to be sorted out first before anybody can start merging or sending PR's. Most PR's are a mess and people started fixing problems for them selfs and mixed fixes and features in a bunch of commits no one understands.

Will take some time but I'll get there :)
