### ISSUE TITLE
Compatibility with whitecube/nova-flexible-content

### ISSUE THREAD

**Issue by nilsE** [epartment/nova-dependency-container#93]
Hi,

i'm trying to make a dependency _inside_ a flexible content layout (with  whitecube/nova-flexible-content), like so:

```
class AddressPrivateLayout extends Layout
    {
        protected $name = 'address-private';
        protected $title = 'private address';

        public function fields()
        {
            return [
                Boolean::make('Check me', 'checkme')

                NovaDependencyContainer::make([
                    Text::make('Dependent')
                ])->dependsOn('checkme', 1),

            (...)

```
...but nothing happens when i check the "Check me" field.
Am i doing something wrong, can you help?

Thanks,
Nils

**Comment by wize-wiz** [comment]
@nilsE The fix is quite simple for the dependency container to work with flexible content, though another problem appears due to duplicated content. There is an issue at flexible content somewhere addressing this problem. They don't have the time to address these issues.

I haven't had the time to send a PR fixing the duplicated content issue, because it might break some stuff I don't know about.

So short story, no. I don't see a quick fix to get both packages to work together without modifying flexible contents code.

**Comment by wize-wiz** [comment]
@nilsE Please verify if [v1.2.10](https://github.com/epartment/nova-dependency-container/releases/tag/1.2.10) solves the problem.

**Comment by nilsE** [comment]
works - thanks a lot!!!
